name: Issue Notifications

on:
  issues:
    types:
      - labeled

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Notify on Critical Issues
      if: contains(github.event.issue.labels.*.name, 'critical')
      run: |
        # Add your notification logic here
        echo "This is a critical issue. Notify someone!"
    - name: Notify on High-Priority Issues
      if: contains(github.event.issue.labels.*.name, 'high-priority')
      run: |
        # Add your notification logic here
        echo "This is a high-priority issue. Notify someone!"
    - name: Notify on Milestone Issues
      if: contains(github.event.issue.labels.*.name, 'milestone')
      run: |
        # Add your notification logic here
        echo "This is a milestone-related issue. Notify someone!"
